# Generated by Django 3.2.4 on 2021-07-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id_user', models.IntegerField(primary_key=True, serialize=False, verbose_name='id del usuario')),
                ('nickname', models.CharField(max_length=50, verbose_name='nombre de usuario')),
                ('correo', models.CharField(max_length=320, verbose_name='correo del usuario')),
                ('contraseña', models.CharField(max_length=25, verbose_name='contraseña del usuario')),
                ('imagen', models.CharField(max_length=1000, verbose_name='imagen usuario')),
            ],
        ),
    ]
